### ISSUE TITLE
locast2dvr reformatting

### ISSUE THREAD

**Issue by wjziv** [RandomNinjaAtk/unraid-templates#17]
> So I messed around with the Unraid XML to contain the internal container network and make it what I considered 'proper' for Unraid. The result was fast XML access, whether it was 'slow to load' or failing to be accessed entirely. I'll continue this conversation on your Unraid template repo.

_Originally posted by @wjziv in https://github.com/RandomNinjaAtk/docker-locast2dvr/issues/2#issuecomment-801149689_

I found the tuner XML to be inaccessible without containing the locast container's network and exposing only the ports necessary for usage. [The XML file applicable.](https://github.com/RandomNinjaAtk/unraid-templates/blob/b904a359a2ff6dc349eb1c31c69b4ca9f8ef3696/randomninjaatk/locast2dvr.xml)

Network should be set to bridge, host should be set to 0.0.0.0, and port 6077 should be mapped.

**Comment by RandomNinjaAtk** [comment]
So that likely won't work, feel free to try it, but from my early testing, you won't get any playback... It's set the way it is because that's the only way I could make it function...
See thread: https://github.com/wouterdebie/locast2dvr/issues/4

**Comment by wjziv** [comment]
I saw the thread and I was dubious at first, but it's working flawlessly on my machine. Since it's a container, I imagine there should be no issue replicating it.
![Screenshot 2021-03-17 11 09 14 AM](https://user-images.githubusercontent.com/29553646/111490473-6f834600-8711-11eb-83a4-f1da5e5389fe.png)

**Comment by RandomNinjaAtk** [comment]
If I can replicate it and know that its working. I'll be sure to update it it. I didn't want to use host, but when I initially tested, it was the only option to make it work...

**Comment by RandomNinjaAtk** [comment]
@wjziv 
Does not work in Plex, emby does work with that configuration though....

Plex reports "Playback Error, could not tune..."

This is exactly the same problem I saw in my early testing, which is why the config is the way it is... feel free to jump on discord

**Comment by RandomNinjaAtk** [comment]
Don't think this will ever be fixed, use locast2tuner. I just created the container and published it.
